.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH CONNIE 1 "September 26, 2010"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
connie \- emulation of an electronic organ like e.g. Vox Continental
.SH SYNOPSIS
.B connie [options]
.SH DESCRIPTION
This manual page documents briefly the
.B connie
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
.nf
\fBconnie\fP is a program that simulates the signal flow of an old 
polyphonic analog organ. It's a jack client with one midi in 
and two audio out ports. 
.sp
Two binaries are supplied:
\fBconnie_i386\fP runs on every i386 processor, 
\fBconnie_sse\fP is optimized for PIII processor (or better) with sse unit.
The wrapper script \fBconnie\fP selects the appropriate binary at runtime.
.sp
Two instruments are available, selected by program option "-i NUM".
\fB-i0\fP selects an organ like "Vox Continental", 
\fB-i1\fP selects a "Poor-Man's-Hammond". 
The continental type has four stops (8", 4", 2" and mixture) and three 
voices (flute=sine, reed=rect and sharp=sawtooth).
The P-M-H has the nine well known stops but only one voice (sine).
Both instruments have tunable percussion, vibrato and reverb effects.
A text based user interface shows drawbars for the stops and effects.
They can be manipulated by typing unshifted or shifted character keys.
On a standard QWERTY keyboard "Q" moves the first drawbar up, "A" down,
"W"/"S" moves the second drawbar, "E"/"D" moves the third etc. 
Option \fB-f\fP selects french (AZERTY) and \fB-g\fP selects german (QWERTZ) layout.
Number keys 0..9 select ten predefined presets.
\fB<SPACE>\fP acts as a panic key and \fB<ESC>\fP quits the program (after asking).
.SH OPTIONS
.TP
.B -a
autoconnect to system:playback ports 
.TP
.B -c CHANNEL
select MIDI channel 1..16, 0=all (default)
.TP
.B -f
use french AZERTY keyboard 
.TP
.B -g
use german QWERTZ keyboard
.TP
.B -h
show help
.TP
.B -i INSTRUMENT
select organ model: 
  0 = connie (default),
  1 = poor-man's-hammond
.TP
.B -m MIDI_PORT
connect to jack midi port
.TP
.B -p FREQUENCY
set concert pitch 220..880 Hz 
.TP
.B -s SCALE
select intonation scale
  0 = Equally Tempered
  1 = Hammond Gears (default)
  2 = Pure Intonation
  3 = Pythagorean
  4 = Meantone 1/4
  5 = Werckmeister III
  6 = Kirnberger III
.TP
.B -t SEMI
transpose -12..+12 semitones
.TP
.B -v
show version
.TP
.B -C configfile
load config file
.TP
.B -U UUID
set jack session UUID
.SH AUTHOR
.nf
The program connie was written by Martin Homuth-Rosemann.
.PP
This manual page was written by Martin Homuth-Rosemann
for the Debian project (and may be used by others).

